subs:
  - url: ""
    insecure: false                           # 是否跳过SSL验证
experimental:
  clash_api:
    external_controller: "192.168.31.1:9095"  # Clash API 控制器地址
dns:
  auto_optimize: true                         # 自动获取本地DNS和做CDN优化
